import Std.Http.Server
import SQLite
import Html
import Routing
import Forms
import Todo

open Std Async
open Std Http Server
open Html
open Routing
open Forms

/-- Handlers below take a concrete `urls : Todo.Urls` (`Todo/Urls.lean`, generated by `urlTree`
from patterns written *there*) -- `application ... using Todo.Urls where ...` below only wires
these already-declared names to handlers, never restating a pattern
(`docs/application-macro-plan.md`'s Phase 3 notes). -/

def render (db : SQLite) (urls : Todo.Urls) (filter : Todo.Filter)
    (renderHtml : Todo.Urls → Array Todo.Item → Array Todo.Item → Todo.Filter → String) :
    ContextAsync (Response Body.Any) := do
  let items ← Todo.list db filter
  let allItems ← Todo.list db .all
  Response.ok.html (renderHtml urls items allItems filter)

/-- Renders the fragment for the filter the client's currently viewing (`HX-Current-URL`) --
what every mutating route responds with. -/
def renderMutation (db : SQLite) (urls : Todo.Urls) (req : Request Body.Stream) :
    ContextAsync (Response Body.Any) :=
  let currentFilter := match req.line.headers.get? (.ofString! "hx-current-url") with
  | some v => Todo.filterFromPath v.value
  | none => .all
  render db urls currentFilter Todo.mutationFragment

def pageHandler (filter : Todo.Filter) (ctx : SQLite) (urls : Todo.Urls)
    (_req : Request Body.Stream) : ContextAsync (Response Body.Any) :=
  render ctx urls filter Todo.page

def addHandler (ctx : SQLite) (urls : Todo.Urls) (req : Request Body.Stream) :
    ContextAsync (Response Body.Any) := do
  let title ← formField req "title"
  Todo.add ctx title
  renderMutation ctx urls req

/-- Swaps one todo's `<li>` into edit mode. Not a mutation (nothing in the DB changes), so unlike
every other route below it targets and returns just that one item, not the whole list section. -/
def editHandler (ctx : SQLite) (urls : Todo.Urls) (id : Nat) (_req : Request Body.Stream) :
    ContextAsync (Response Body.Any) := do
  let items ← Todo.list ctx .all
  match items.find? (fun item => item.id == Int64.ofNat id) with
  | some item => Response.ok.html (Node.render (Todo.itemEditView urls item))
  | none => Response.notFound.text "Not Found"

def saveHandler (ctx : SQLite) (urls : Todo.Urls) (id : Nat) (req : Request Body.Stream) :
    ContextAsync (Response Body.Any) := do
  let title ← formField req "title"
  Todo.setTitle ctx (Int64.ofNat id) title
  renderMutation ctx urls req

def toggleHandler (ctx : SQLite) (urls : Todo.Urls) (id : Nat) (req : Request Body.Stream) :
    ContextAsync (Response Body.Any) := do
  Todo.toggle ctx (Int64.ofNat id)
  renderMutation ctx urls req

def deleteHandler (ctx : SQLite) (urls : Todo.Urls) (id : Nat) (req : Request Body.Stream) :
    ContextAsync (Response Body.Any) := do
  Todo.delete ctx (Int64.ofNat id)
  renderMutation ctx urls req

def toggleAllHandler (ctx : SQLite) (urls : Todo.Urls) (req : Request Body.Stream) :
    ContextAsync (Response Body.Any) := do
  Todo.toggleAll ctx
  renderMutation ctx urls req

def clearCompletedHandler (ctx : SQLite) (urls : Todo.Urls) (req : Request Body.Stream) :
    ContextAsync (Response Body.Any) := do
  Todo.clearCompleted ctx
  renderMutation ctx urls req

application app : SQLite using Todo.Urls where
  index { get => pageHandler .all }
  active { get => pageHandler .active }
  completed { get => pageHandler .completed }
  todos {
    post => addHandler
    todo {
      put => saveHandler
      delete => deleteHandler
      todoEdit { get => editHandler }
      todoToggle { post => toggleHandler }
    }
    toggleAll { post => toggleAllHandler }
    clearCompleted { delete => clearCompletedHandler }
  }

/-! ## Regression against the *real* generated `app`, not just `Routing.Application`'s toy harness

Confirms `application`'s concrete claim (`docs/application-macro-plan.md` §1) for this app's actual
patterns, and -- since nothing in `TodoTests` otherwise exercises HTTP dispatch -- that the real
route table and the real `Urls` values agree, the same way `Routing.Application`'s own `#eval
runGroup` regressions do (`Routing/Application.lean`). -/

#guard app.urls.index = "/"
#guard app.urls.active = "/active"
#guard app.urls.completed = "/completed"
#guard app.urls.todos = "/todos"
#guard app.urls.todo 7 = "/todos/7"
#guard app.urls.todoEdit 7 = "/todos/7/edit"
#guard app.urls.todoToggle 7 = "/todos/7/toggle"
#guard app.urls.toggleAll = "/todos/toggle-all"
#guard app.urls.clearCompleted = "/todos/completed"

open Std.Http.Internal.Test in
private def freshAppHandler : IO TestHandler := do
  let db ← SQLite.open ":memory:"
  Todo.initSchema db
  pure (app.handler db).onRequest

open Std.Http.Internal.Test in
#eval runGroup "Main.app" do
  let handler ← freshAppHandler
  checkClose "index page renders" (mkGet "/") handler (assertContains · "todos")
  checkClose "add dispatches through the real flattened route table" (mkPost "/todos" "title=Buy+milk")
    handler (assertContains · "Buy milk")
  checkClose "toggle-all beats the same-arity /:id:Nat capture" (mkPost "/todos/toggle-all" "")
    handler (fun r => assertStatus r "HTTP/1.1 200")

def main : IO Unit := Async.block do
  let db ← SQLite.open ":memory:"
  Todo.initSchema db
  let addr := .v4 ⟨.ofParts 127 0 0 1, 2000⟩
  serve addr (app.handler db) >>= waitShutdown
