import Routing.RouteTable

/-!
Route pattern strings and their reverse-routing `Links`, generated by `Routing.routeTable!`
(`Routing/RouteTable.lean`) from one list of `pattern as name` rows -- so a path only ever appears
in source once, rather than as separately hand-maintained pattern strings (for `Main.lean`'s
dispatch table) and literal path strings (in `Todo/Views.lean`'s `hx-*` attributes). `todo` is
declared once despite backing two HTTP methods (`PUT`/`DELETE` on the same URL in `Main.lean`) --
a link name denotes a URL, not a method.
-/

routeTable! Todo
  [ "/"                      as index,
    "/active"                as active,
    "/completed"             as completed,
    "/todos"                 as todos,
    "/todos/:id:Nat"         as todo,
    "/todos/:id:Nat/edit"    as edit,
    "/todos/:id:Nat/toggle"  as toggle,
    "/todos/toggle-all"      as toggleAll,
    "/todos/clear-completed" as clearCompleted ]

#guard Todo.links.index = "/"
#guard Todo.links.active = "/active"
#guard Todo.links.completed = "/completed"
#guard Todo.links.todos = "/todos"
#guard Todo.links.toggleAll = "/todos/toggle-all"
#guard Todo.links.clearCompleted = "/todos/clear-completed"
#guard Todo.links.todo 7 = "/todos/7"
#guard Todo.links.edit 7 = "/todos/7/edit"
#guard Todo.links.toggle 7 = "/todos/7/toggle"
